package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
)

// completionShellNames are the shells supported by `semantix completion`.
var completionShellNames = []string{"bash", "zsh", "fish"}

// runCompletion implements the U23 shell completion generator (Issue #117):
// `semantix completion bash|zsh|fish` prints a static completion script for
// the current command tree. Word lists are derived from the same `commands`
// registry that dispatch and help use, so completion can never drift from
// the tree itself (TestCompletionFlagsMatchCommandHelp locks the flag lists
// against each command's --help output).
func runCompletion(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("completion", flag.ContinueOnError)
	fs.SetOutput(stderr)
	if err := fs.Parse(args); err != nil {
		if errors.Is(err, flag.ErrHelp) {
			return 0 // --help is a successful request
		}
		return 2
	}
	if fs.NArg() != 1 {
		fmt.Fprintf(stderr, "semantix completion: missing or extra shell argument (want %s)\n",
			strings.Join(completionShellNames, ", "))
		fmt.Fprintln(stderr, "usage: semantix completion bash|zsh|fish")
		return 2
	}
	shell := fs.Arg(0)
	var script string
	switch shell {
	case "bash":
		script = completionScriptBash()
	case "zsh":
		script = completionScriptZsh()
	case "fish":
		script = completionScriptFish()
	default:
		fmt.Fprintf(stderr, "semantix completion: unsupported shell %q (want %s)\n",
			shell, strings.Join(completionShellNames, ", "))
		return 2
	}
	fmt.Fprint(stdout, script)
	return 0
}

// completionEntry is one row of the completion word table: a registered
// command plus the candidates the generated scripts offer for it. `words`
// covers commands whose completions are positional values rather than flags
// (completion -> shells, help -> command names).
type completionEntry struct {
	name    string
	summary string
	flags   []string            // --flag candidates (sorted, --help included)
	values  map[string][]string // flag -> closed-set value candidates
	words   []string            // positional candidates (sorted)
}

// completionTree builds the completion word table from the U19 command
// registry. It is the single source of truth for every generated script.
func completionTree() []completionEntry {
	entries := make([]completionEntry, 0, len(commands)+2)
	for _, c := range commands {
		e := completionEntry{
			name:    c.name,
			summary: c.summary,
			flags:   commandFlagList(c),
			values:  c.flagValues,
		}
		if c.name == "completion" {
			// completion takes positional shells, not flags.
			e.flags = nil
			e.words = append([]string(nil), completionShellNames...)
		}
		entries = append(entries, e)
	}
	// help is dispatched by run() outside the registry; give it command
	// names so `semantix help <TAB>` completes.
	entries = append(entries, completionEntry{
		name:    "help",
		summary: "list commands by group, or show one command's synopsis",
		words:   commandNameList(),
	})
	return entries
}

// commandFlagList returns the completion candidates for one command's flags:
// its declared completionFlags plus --help, deduplicated and sorted so the
// generated scripts are deterministic.
func commandFlagList(c commandSpec) []string {
	seen := map[string]bool{}
	var out []string
	for _, f := range c.completionFlags {
		if !seen[f] {
			seen[f] = true
			out = append(out, f)
		}
	}
	if !seen["--help"] {
		out = append(out, "--help")
	}
	sort.Strings(out)
	return out
}

// commandNameList returns every registered command name plus help, sorted.
func commandNameList() []string {
	out := make([]string, 0, len(commands)+1)
	for _, c := range commands {
		out = append(out, c.name)
	}
	out = append(out, "help")
	sort.Strings(out)
	return out
}

// sortedValues returns a flag's closed-set value candidates, sorted.
func sortedValues(values map[string][]string, flagName string) []string {
	out := append([]string(nil), values[flagName]...)
	sort.Strings(out)
	return out
}

// valueFlagNames returns the flags that have closed-set values, sorted.
func valueFlagNames(values map[string][]string) []string {
	out := make([]string, 0, len(values))
	for f := range values {
		out = append(out, f)
	}
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------------------
// bash

func completionScriptBash() string {
	var b strings.Builder
	b.WriteString("# bash completion for semantix (generated by `semantix completion bash`)\n")
	b.WriteString("# load with:  source <(semantix completion bash)\n")
	b.WriteString("_semantix() {\n")
	b.WriteString("    local cur prev\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    if [[ ${COMP_CWORD} -eq 1 ]]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W \"")
	b.WriteString(strings.Join(commandNameList(), " "))
	b.WriteString("\" -- \"${cur}\") )\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n")
	b.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	b.WriteString("    case \"${COMP_WORDS[1]}\" in\n")
	for _, e := range completionTree() {
		fmt.Fprintf(&b, "        %s)\n", e.name)
		if len(e.words) > 0 {
			fmt.Fprintf(&b, "            COMPREPLY=( $(compgen -W \"%s\" -- \"${cur}\") )\n",
				strings.Join(e.words, " "))
		} else {
			for _, vf := range valueFlagNames(e.values) {
				fmt.Fprintf(&b, "            case \"${prev}\" in\n")
				fmt.Fprintf(&b, "                %s) COMPREPLY=( $(compgen -W \"%s\" -- \"${cur}\") ); return ;;\n",
					vf, strings.Join(sortedValues(e.values, vf), " "))
				fmt.Fprintf(&b, "            esac\n")
			}
			fmt.Fprintf(&b, "            COMPREPLY=( $(compgen -W \"%s\" -- \"${cur}\") )\n",
				strings.Join(e.flags, " "))
		}
		b.WriteString("            ;;\n")
	}
	b.WriteString("    esac\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _semantix semantix\n")
	return b.String()
}

// ---------------------------------------------------------------------------
// zsh

// zshQuote wraps s in single quotes, escaping embedded quotes with the
// classic backslash-quote splice so arbitrary summaries (e.g. "command's")
// stay valid zsh source.
func zshQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func completionScriptZsh() string {
	var b strings.Builder
	b.WriteString("#compdef semantix\n")
	b.WriteString("# zsh completion for semantix (generated by `semantix completion zsh`)\n")
	b.WriteString("# load with:  source <(semantix completion zsh)   (after compinit)\n")
	b.WriteString("_semantix() {\n")
	b.WriteString("    local -a _semantix_commands _semantix_flags\n")
	b.WriteString("    _semantix_commands=(\n")
	for _, e := range completionTree() {
		fmt.Fprintf(&b, "        %s\n", zshQuote(e.name+":"+e.summary))
	}
	b.WriteString("    )\n")
	b.WriteString("    if (( CURRENT == 2 )); then\n")
	b.WriteString("        _describe -t semantix-commands 'semantix command' _semantix_commands\n")
	b.WriteString("        return\n")
	b.WriteString("    fi\n")
	b.WriteString("    case \"${words[2]}\" in\n")
	for _, e := range completionTree() {
		fmt.Fprintf(&b, "        %s)\n", e.name)
		switch {
		case len(e.words) > 0:
			b.WriteString("            _describe -t semantix-words 'candidate'")
			for _, w := range e.words {
				fmt.Fprintf(&b, " '%s:%s'", w, w)
			}
			b.WriteString("\n")
		case len(e.values) > 0:
			for _, vf := range valueFlagNames(e.values) {
				fmt.Fprintf(&b, "            case \"${words[CURRENT-1]}\" in\n")
				fmt.Fprintf(&b, "                %s) _describe -t semantix-values '%s'", vf, strings.TrimPrefix(vf, "--"))
				for _, v := range sortedValues(e.values, vf) {
					fmt.Fprintf(&b, " '%s:%s'", v, v)
				}
				b.WriteString("; return ;;\n")
				b.WriteString("            esac\n")
			}
			b.WriteString("            _semantix_flags=(")
			for _, f := range e.flags {
				fmt.Fprintf(&b, " %s", f)
			}
			b.WriteString(" )\n")
			b.WriteString("            _describe -t semantix-flags 'flag' _semantix_flags\n")
		default:
			b.WriteString("            _semantix_flags=(")
			for _, f := range e.flags {
				fmt.Fprintf(&b, " %s", f)
			}
			b.WriteString(" )\n")
			b.WriteString("            _describe -t semantix-flags 'flag' _semantix_flags\n")
		}
		b.WriteString("            ;;\n")
	}
	b.WriteString("    esac\n")
	b.WriteString("}\n")
	b.WriteString("compdef _semantix semantix\n")
	return b.String()
}

// ---------------------------------------------------------------------------
// fish

func completionScriptFish() string {
	var b strings.Builder
	b.WriteString("# fish completion for semantix (generated by `semantix completion fish`)\n")
	b.WriteString("# load with:  semantix completion fish | source\n")
	b.WriteString("complete -c semantix -f\n")
	for _, e := range completionTree() {
		fmt.Fprintf(&b, "complete -c semantix -n '__fish_use_subcommand' -a %s -d '%s'\n",
			e.name, strings.ReplaceAll(e.summary, "'", "\\'"))
	}
	for _, e := range completionTree() {
		if len(e.words) > 0 {
			for _, w := range e.words {
				fmt.Fprintf(&b, "complete -c semantix -n '__fish_seen_subcommand_from %s' -a %s\n",
					e.name, w)
			}
			continue
		}
		for _, f := range e.flags {
			fmt.Fprintf(&b, "complete -c semantix -n '__fish_seen_subcommand_from %s' -l %s\n",
				e.name, strings.TrimPrefix(f, "--"))
		}
		for _, vf := range valueFlagNames(e.values) {
			fmt.Fprintf(&b, "complete -c semantix -n '__fish_seen_subcommand_from %s; and __fish_seen_subcommand_from %s' -a '%s'\n",
				e.name, vf, strings.Join(sortedValues(e.values, vf), " "))
		}
	}
	return b.String()
}
